### ISSUE TITLE
Complete outer query not working

### ISSUE THREAD

**Issue by cccs-jc** [joe-re/sql-language-server#115]
Given the following statement ctrl-space at char 8th, to complete the alias fails
```sql
SELECT t FROM (SELECT col1 FROM table1 as tab)
```
The error is 

[2022-02-06] [DEBUG] default - TypeError: Cannot read properties of null (reading 'startsWith')
    at Identifier.matchesLastToken (/opt/conda/lib/node_modules/sql-language-server/dist/src/complete.js:50:29)
    at /opt/conda/lib/node_modules/sql-language-server/dist/src/complete.js:289:34
    at Array.filter (<anonymous>)
    at Completer.addCandidatesForTables (/opt/conda/lib/node_modules/sql-language-server/dist/src/complete.js:289:14)
    at Completer.addCandidatesForParsedSelectQuery (/opt/conda/lib/node_modules/sql-language-server/dist/src/complete.js:485:22)
    at Completer.addCandidatesForParsedStatement (/opt/conda/lib/node_modules/sql-language-server/dist/src/complete.js:502:18)
    at Completer.complete (/opt/conda/lib/node_modules/sql-language-server/dist/src/complete.js:148:18)
    at complete (/opt/conda/lib/node_modules/sql-language-server/dist/src/complete.js:656:34)
    at /opt/conda/lib/node_modules/sql-language-server/dist/src/createServer.js:206:52
    at /opt/conda/lib/node_modules/sql-language-server/node_modules/vscode-languageserver/lib/common/server.js:678:20

**Comment by joe-re** [comment]
@cccs-jc 
Hi, thanks for your report. We need to handle the error though, is it the right grammar for some DBs?
I've just tried it on Postgres though, it doesn't go well with alias since select clauses on subquery should have an alias on outside of parens.
Hence, we should show a syntax error rather than showing the alias completion I think.

```
postgres_db=# select * from (select * from "Users" as U);
ERROR:  subquery in FROM must have an alias
LINE 1: select * from (select * from "Users" as U);
 ```

If you put the alias to outside of parens, it works.
```
postgres_db=# select * from (select * from "Users") as U;
 id | firstName | lastName | email | createdAt | updatedAt
----+-----------+----------+-------+-----------+-----------
(0 rows)
```

If you have some information or opinions please share me. 🙏

**Comment by cccs-jc** [comment]
You are totally right @joe-re. My mistake. I'm closing this issue.

Cheers
