### ISSUE TITLE
Can't  auto complete database.table.column simultaneously. 

### ISSUE THREAD

**Issue by pltf492325129** [joe-re/sql-language-server#193]
1、When using a Spark schema JSON file in jupyterlab for auto-completion, it can't  auto complete database.table.column simultaneously. Only database.table or table.column auto-completion is supported. 

![image](https://user-images.githubusercontent.com/49930095/236775527-45aa521f-2393-4fd4-97e0-5718f5e3be6a.png)
![image](https://user-images.githubusercontent.com/49930095/236775638-a9743534-d88a-4e39-9940-9726c8415bf9.png)
![image](https://user-images.githubusercontent.com/49930095/236775882-961c91d3-f391-4775-9cb8-bcb48060de88.png)

2、Why doesn't it treat dli as consecutive characters and then support custom sorting
![image](https://user-images.githubusercontent.com/49930095/236795129-af557931-0c57-45ce-8188-d173182d0017.png)

3、When using lowercase keywords, is it possible to complete uppercase keywords in the future.

**Comment by joe-re** [comment]
@pltf492325129 Hi, thanks for your report. If you type dot after table(`database.table.`), it still can't complete a column?

**Comment by pltf492325129** [comment]
> @pltf492325129 Hi, thanks for your report. If you type dot after table(`database.table.`), it still can't complete a column?

Yes, it still can't complete a column when I type dot after table.
![image](https://github.com/joe-re/sql-language-server/assets/49930095/73243910-4c1b-4aa2-ba51-0f61c257b5bd)

log:
```
[2023-05-29T15:39:18.256] [DEBUG] default - complete: SELECT * FROM default.COMPANY.
, {"line":0,"column":30}
[2023-05-29T15:39:18.256] [DEBUG] default - target: SELECT * FROM default.COMPANY.
[2023-05-29T15:39:18.256] [DEBUG] default - error
[2023-05-29T15:39:18.256] [DEBUG] default - peg$SyntaxError: Expected "$", "--", "/*", "\"", "`", [ \t\n\r], or [A-Za-z_] but end of input found.
    at peg$buildStructuredError (/home/z00798141/anaconda3/envs/test/share/jupyter/lab/staging/node_modules/@joe-re/sql-parser/base/parser.js:1490:12)
    at Object.peg$parse [as parse] (/home/z00798141/anaconda3/envs/test/share/jupyter/lab/staging/node_modules/@joe-re/sql-parser/base/parser.js:14638:11)
    at exports.parse (/home/z00798141/anaconda3/envs/test/share/jupyter/lab/staging/node_modules/@joe-re/sql-parser/index.js:7:19)
    at Completer.complete (/home/z00798141/anaconda3/envs/test/share/jupyter/lab/staging/node_modules/sql-language-server/dist/src/complete/complete.js:54:48)
    at complete (/home/z00798141/anaconda3/envs/test/share/jupyter/lab/staging/node_modules/sql-language-server/dist/src/complete/complete.js:309:34)
    at /home/z00798141/anaconda3/envs/test/share/jupyter/lab/staging/node_modules/sql-language-server/dist/src/createServer.js:226:52
    at /home/z00798141/anaconda3/envs/test/share/jupyter/lab/staging/node_modules/vscode-languageserver/lib/common/server.js:567:20
    at handleRequest (/home/z00798141/anaconda3/envs/test/share/jupyter/lab/staging/node_modules/vscode-languageserver/node_modules/vscode-jsonrpc/lib/common/connection.js:438:41)
    at processMessageQueue (/home/z00798141/anaconda3/envs/test/share/jupyter/lab/staging/node_modules/vscode-languageserver/node_modules/vscode-jsonrpc/lib/common/connection.js:302:17)
    at Immediate._onImmediate (/home/z00798141/anaconda3/envs/test/share/jupyter/lab/staging/node_modules/vscode-languageserver/node_modules/vscode-jsonrpc/lib/common/connection.js:292:13) {
  expected: [
    {
      type: 'class',
      parts: [Array],
      inverted: false,
      ignoreCase: false
    },
    { type: 'literal', text: '--', ignoreCase: false },
    { type: 'literal', text: '/*', ignoreCase: false },
    {
      type: 'class',
      parts: [Array],
      inverted: false,
      ignoreCase: false
    },
    { type: 'literal', text: '`', ignoreCase: false },
    { type: 'literal', text: '"', ignoreCase: false },
    { type: 'literal', text: '$', ignoreCase: false },
    { type: 'literal', text: '$', ignoreCase: false }
  ],
  found: null,
  location: {
    start: { offset: 30, line: 1, column: 31 },
    end: { offset: 30, line: 1, column: 31 }
  }
}
[2023-05-29T15:39:18.256] [DEBUG] default - candidates for error returns: []
[2023-05-29T15:39:18.257] [DEBUG] default - onCompletion returns: []
```

**Comment by pltf492325129** [comment]
@joe-re  hi, I think there was a problem with this when I made the following modifications and everything worked fine.

```
    addCandidatesForScopedColumns(fromNodes, tables) {
        console.time('addCandidatesForScopedColumns');
        **if (this.lastToken.match(/\./g).length > 1) {
            this.lastToken = this.lastToken.substring( this.lastToken.indexOf('.') + 1);
        }**
...
```

**Comment by joe-re** [comment]
@pltf492325129 Hi, thanks for your report but I was not able to find where you point. Can I know which version of sql-language-server you use?
