### ISSUE TITLE
sqlint exception

### ISSUE THREAD

**Issue by zjuyxy** [joe-re/sql-language-server#36]
The same .sqlintrc.json content both in project folder and personal folder as:
{
    "rules": {
      "align-column-to-the-first": 0,
      "column-new-line": 0,
      "linebreak-after-clause-keyword": 0,
      "reserved-word-case": [0,"upper"],
      "space-surrounding-operators": 0,
      "where-clause-new-line": 0
    }
  }

It's a bit of wired that this error only appears twice.

Error: No files matching 'undefined' were found.
    at lint (/home/xxxx/.vscode/extensions/joe-re.sql-language-server-0.10.7/packages/server/dist/cli.js:69491:15)
    at doLint (/home/xxxx/.vscode/extensions/joe-re.sql-language-server-0.10.7/packages/server/dist/cli.js:69557:31)
    at createDiagnostics (/home/xxxx/.vscode/extensions/joe-re.sql-language-server-0.10.7/packages/server/dist/cli.js:69583:23)
    at /home/xxxx/.vscode/extensions/joe-re.sql-language-server-0.10.7/packages/server/dist/cli.js:106849:29
    at CallbackList.invoke (/home/xxxx/.vscode/extensions/joe-re.sql-language-server-0.10.7/packages/server/dist/cli.js:9282:39)
    at Emitter.fire (/home/xxxx/.vscode/extensions/joe-re.sql-language-server-0.10.7/packages/server/dist/cli.js:9341:36)
    at /home/xxxx/.vscode/extensions/joe-re.sql-language-server-0.10.7/packages/server/dist/cli.js:15155:38
    at handleNotification (/home/xxxx/.vscode/extensions/joe-re.sql-language-server-0.10.7/packages/server/dist/cli.js:10765:43)
    at processMessageQueue (/home/xxxx/.vscode/extensions/joe-re.sql-language-server-0.10.7/packages/server/dist/cli.js:10536:17)
    at Immediate._onImmediate (/home/xxxx/.vscode/extensions/joe-re.sql-language-server-0.10.7/packages/server/dist/cli.js:10523:13)

LSP diagnotiscs work fine after this error
![image](https://user-images.githubusercontent.com/3321614/85983200-aac1d580-ba19-11ea-8cb5-b96156f9e09c.png)

**Comment by joe-re** [comment]
@zjuyxy Thank you for your report! I'll take a look.

**Comment by joe-re** [comment]
@zjuyxy Hi, I've fixed it. Actually this error happened when the text was empty and it didn't affect to working itself. (That is why you only see this error twice.)
If you find something wrong more please reopen it.
Thanks.
