### ISSUE TITLE
Issue building vscode extension

### ISSUE THREAD

**Issue by cccs-jc** [joe-re/sql-language-server#80]
@joe-re In my pull request you will see that I've added a dependency on CompletionTriggerKind. 

I can build the server and test it with JupyterLab no problem using this build command
```
sql-language-server/packages/server$ npm run prepublish
```

I would now like to build it for vscode using this command.
```
sql-language-server/packages/server$ npm run prepare-vsc-extension
```

However I get this error
```
[!] Error: 'CompletionTriggerKind' is not exported by node_modules/vscode-languageserver/node.js, imported by src/createServer.ts
https://rollupjs.org/guide/en/#error-name-is-not-exported-by-module
src/createServer.ts (1:9)
1: import { CompletionTriggerKind, } from 'vscode-languageserver/node';
            ^
2: import * as VscodeNode from 'vscode-languageserver/node';
3: import { TextDocument } from 'vscode-languageserver-textdocument';
Error: 'CompletionTriggerKind' is not exported by node_modules/vscode-languageserver/node.js, imported by src/createServer.ts
    at error (/Users/jc/jupyter-ext/sql-language-server/packages/server/node_modules/rollup/dist/shared/rollup.js:151:30)
    at Module.error (/Users/jc/jupyter-ext/sql-language-server/packages/server/node_modules/rollup/dist/shared/rollup.js:10059:16)
    at Module.traceVariable (/Users/jc/jupyter-ext/sql-language-server/packages/server/node_modules/rollup/dist/shared/rollup.js:10444:29)
    at ModuleScope.findVariable (/Users/jc/jupyter-ext/sql-language-server/packages/server/node_modules/rollup/dist/shared/rollup.js:9227:39)
    at FunctionScope.findVariable (/Users/jc/jupyter-ext/sql-language-server/packages/server/node_modules/rollup/dist/shared/rollup.js:3654:38)
    at ChildScope.findVariable (/Users/jc/jupyter-ext/sql-language-server/packages/server/node_modules/rollup/dist/shared/rollup.js
```

I'm not familiar with what rollup does but I suspect the issue might be with that script. Any help would be much appreciated. Thanks

**Comment by joe-re** [comment]
@cccs-jc I think I have an idea to fix the above error. I'll work on it after merged your PR to release the new version. Thanks for your report!

**Comment by joe-re** [comment]
fixed by https://github.com/joe-re/sql-language-server/pull/88. Thanks
