### ISSUE TITLE
Error occur when installing via npm

### ISSUE THREAD

**Issue by shizuku** [joe-re/sql-language-server#89]
I install sql-language-server using command `npm i -g sql-language-server` in order to use in `neovim` with `coc.nvim`.

There are some error occur:
```
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated node-pre-gyp@0.11.0: Please upgrade to @mapbox/node-pre-gyp: the non-scoped node-pre-gyp package is deprecated and only the @mapbox scoped package will recieve updates in the future
npm ERR! code 1
npm ERR! path /home/shizuku/.volta/tmp/image/packages/.tmpO7NgTt/lib/node_modules/sql-language-server/node_modules/sqlite3
npm ERR! command failed
npm ERR! command sh -c node-gyp rebuild
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@7.1.2
npm ERR! gyp info using node@16.9.0 | linux | x64
npm ERR! gyp info find Python using Python version 3.9.7 found at "/usr/bin/python3"
npm ERR! (node:13958) [DEP0150] DeprecationWarning: Setting process.config is deprecated. In the future the property will be read-only.
npm ERR! (Use `node --trace-deprecation ...` to show where the warning was created)
npm ERR! gyp info spawn /usr/bin/python3
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   '/home/shizuku/.volta/tools/image/npm/7.24.1/node_modules/node-gyp/gyp/gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'make',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/home/shizuku/.volta/tmp/image/packages/.tmpO7NgTt/lib/node_modules/sql-language-server/node_modules/sqlite3/build/config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/home/shizuku/.volta/tools/image/npm/7.24.1/node_modules/node-gyp/addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/home/shizuku/.cache/node-gyp/16.9.0/include/node/common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=/home/shizuku/.cache/node-gyp/16.9.0',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/home/shizuku/.volta/tools/image/npm/7.24.1/node_modules/node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=/home/shizuku/.cache/node-gyp/16.9.0/<(target_arch)/node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=/home/shizuku/.volta/tmp/image/packages/.tmpO7NgTt/lib/node_modules/sql-language-server/node_modules/sqlite3',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! gyp: Undefined variable module_name in binding.gyp while trying to load binding.gyp
npm ERR! gyp ERR! configure error
npm ERR! gyp ERR! stack Error: `gyp` failed with exit code: 1
npm ERR! gyp ERR! stack     at ChildProcess.onCpExit (/home/shizuku/.volta/tools/image/npm/7.24.1/node_modules/node-gyp/lib/configure.js:351:16)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:394:28)
npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
npm ERR! gyp ERR! System Linux 5.14.9-arch2-1
npm ERR! gyp ERR! command "/home/shizuku/.volta/tools/image/node/16.9.0/bin/node" "/home/shizuku/.volta/tools/image/npm/7.24.1/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
npm ERR! gyp ERR! cwd /home/shizuku/.volta/tmp/image/packages/.tmpO7NgTt/lib/node_modules/sql-language-server/node_modules/sqlite3
npm ERR! gyp ERR! node -v v16.9.0
npm ERR! gyp ERR! node-gyp -v v7.1.2
npm ERR! gyp ERR! not ok

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/shizuku/.npm/_logs/2021-10-11T03_29_03_943Z-debug.log
```

os: Archlinux
node: 16.9.0 (from volta)
npm: 7.24.1

**Comment by joe-re** [comment]
@shizuku Hi, thanks for your report. It looks like sqlite3 and node-gyp problem to build a binary file.
Can you make sure that you can install sqlite3 itself, by `npm install sqlite3 -g` ?

**Comment by shizuku** [comment]
> @shizuku Hi, thanks for your report. It looks like sqlite3 and node-gyp problem to build a binary file. Can you make sure that you can install sqlite3 itself, by `npm install sqlite3 -g` ?

thank you, i tried `npm install sqlite3 -g`, which got ERROR too:
```
npm WARN deprecated har-validator@5.1.5: this
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated node-pre-gyp@0.11.0: Please upgrade to @mapbox/node-pre-gyp: the non-scoped node-pre-gyp package is deprecated and only the @mapbox scoped package will recieve updates in the future
npm WARN deprecated tar@2.2.2: This version of tar is no longer supported, and will not receive security updates. Please upgrade asap.
npm ERR! code 1
npm ERR! path /home/shizuku/.volta/tmp/image/packages/.tmp4zjj6a/lib/node_modules/sqlite3
npm ERR! command failed
npm ERR! command sh -c node-gyp rebuild
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@3.8.0
npm ERR! gyp info using node@15.14.0 | linux | x64
npm ERR! gyp info spawn /usr/bin/python2
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   '/home/shizuku/.volta/tmp/image/packages/.tmp4zjj6a/lib/node_modules/sqlite3/node_modules/node-gyp/gyp/gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'make',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/home/shizuku/.volta/tmp/image/packages/.tmp4zjj6a/lib/node_modules/sqlite3/build/config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/home/shizuku/.volta/tmp/image/packages/.tmp4zjj6a/lib/node_modules/sqlite3/node_modules/node-gyp/addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/home/shizuku/.node-gyp/15.14.0/include/node/common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=/home/shizuku/.node-gyp/15.14.0',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/home/shizuku/.volta/tmp/image/packages/.tmp4zjj6a/lib/node_modules/sqlite3/node_modules/node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=/home/shizuku/.node-gyp/15.14.0/<(target_arch)/node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=/home/shizuku/.volta/tmp/image/packages/.tmp4zjj6a/lib/node_modules/sqlite3',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! gyp: Undefined variable module_name in binding.gyp while trying to load binding.gyp
npm ERR! gyp ERR! configure error
npm ERR! gyp ERR! stack Error: `gyp` failed with exit code: 1
npm ERR! gyp ERR! stack     at ChildProcess.onCpExit (/home/shizuku/.volta/tmp/image/packages/.tmp4zjj6a/lib/node_modules/sqlite3/node_modules/node-gyp/lib/configure.js:345:16)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:369:20)
npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
npm ERR! gyp ERR! System Linux 5.14.9-arch2-1
npm ERR! gyp ERR! command "/home/shizuku/.volta/tools/image/node/15.14.0/bin/node" "/home/shizuku/.volta/tmp/image/packages/.tmp4zjj6a/lib/node_modules/sqlite3/node_modules/.bin/node-gyp" "rebuild"
npm ERR! gyp ERR! cwd /home/shizuku/.volta/tmp/image/packages/.tmp4zjj6a/lib/node_modules/sqlite3
npm ERR! gyp ERR! node -v v15.14.0
npm ERR! gyp ERR! node-gyp -v v3.8.0
npm ERR! gyp ERR! not ok

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/shizuku/.npm/_logs/2021-10-11T04_35_42_398Z-debug.log
```
Howerver, i tried `yarn global add sqlite3` and `yarn global add sql-language-server`, which works.

 I dont't know why but it seems solved by using `yarn`.

**Comment by joe-re** [comment]
@shizuku Seems like npm@7.x.x causes the problem. https://github.com/nodejs/node-gyp/issues/508
I'm not sure the problem is still persistent or not since I can install sqlite3 by using npm@7.0.14.
Probably updating npm version(or downgrade) may fix the problem.
If this problem is solved for you, please close this issue. Thanks.

**Comment by shizuku** [comment]
@joe-re It seems not work by using npm@7.0.14, too. npm@6.14.15 got much errors but seems installed sucessfully. I think it solved by using `yarn`. so i will close this issue.
